Add sampler: log uniform
rwth-i6/i6_models pull request #64
Opened 2024-12-18 17:17 UTC by christophmluscher

Adds a sampler for NCE loss

Implemented by @Gerstenberger

2024-12-18 17:28 UTC, albertz commented on i6_models/samplers/log_uniform.py
> +        self._distribution /= self._distribution.sum()
Why first make a Python list of Python floats? Why not use Torch right away?
```suggestion
        ws = torch.arange(self.num_classes, dtype=torch.get_default_dtype())
        self._distribution = (torch.log1p(ws + 1) - torch.log1p(ws)) / torch.log1p(torch.tensor(self.num_classes))
        self._distribution.clamp_(min=1e-10)
        self._distribution /= self._distribution.sum()
```

2024-12-18 17:30 UTC, albertz commented on i6_models/samplers/log_uniform.py
> +        self._cat_sampler = torch.distributions.categorical.Categorical(probs=self._distribution.cuda())
```suggestion
        self._cat_sampler = torch.distributions.categorical.Categorical(probs=self._distribution)
```

2025-01-10 13:40 UTC, curufinwe requested changes

2025-01-10 13:40 UTC, curufinwe commented on i6_models/samplers/log_uniform.py
> +class LogUniformSampler(nn.Module):
This class is a subclass of nn.Module, which makes it a part and thus should be in the parts folder instead of a dedicated samplers folder.

2025-01-16 13:08 UTC, JackTemaki requested changes

2025-01-16 13:08 UTC, JackTemaki commented on i6_models/parts/samplers/log_uniform.py
> +    def sample(self, num_samples: int) -> torch.Tensor:
It would be nice to have the shapes documented for sample and log_prob.

2025-01-16 13:08 UTC, JackTemaki commented on i6_models/parts/samplers/log_uniform.py
> +        self._distribution.clamp_(min=1e-10)
Is this always a safe choice, or does this need to be configurable?

2025-01-16 16:11 UTC, christophmluscher commented on i6_models/parts/samplers/log_uniform.py
> +        self._distribution.clamp_(min=1e-10)
not sure. I ll make it configurable but define a default value.

2025-01-28 21:54 UTC, JackTemaki approved these changes

2025-01-29 09:20 UTC, curufinwe approved these changes

2025-01-29 09:20 UTC, merged